### PR TITLE
Ability to disable JinjaCpp installation rules

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
- When JinjaCpp is build as sub-project and used as static library, installation rules are not required. It's a good practice to disable installation rules when project is used as a subproject.
- Secondly, cloning of boost repository takes a while, while download archive is more compact and fast way.
- Migrated to new 1.85 boost version, which does not require patching

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Hi @rmorozov 
Could you please review?

**Comment by ilya-lavrenov** [comment]
> @ilya-lavrenov , sure, could you please fix CI errors?
> 
> If you don't have access to info about errors - let me know.

I've experienced the same error locally even w/o my changes. 

Is it possible to run CI on latest master to confirm it?

**Comment by rmorozov** [comment]
> > @ilya-lavrenov , sure, could you please fix CI errors?
> > If you don't have access to info about errors - let me know.
> 
> I've experienced the same error locally even w/o my changes.
> 
> Is it possible to run CI on latest master to confirm it?

@ilya-lavrenov , sure, I have run it on https://github.com/jinja2cpp/Jinja2Cpp/pull/251

CI is green, so it seems that error connected with new changes in this PR

**Comment by ilya-lavrenov** [comment]
Hi @rmorozov 
I've updated the branch. Could you please run CI?

**Comment by ilya-lavrenov** [comment]
Hi @rmorozov 
I've updated the branch. Could you please run CI?

**Comment by rmorozov** [comment]
@ilya-lavrenov , Seems fine now

thank you for your effort

**Pull request merged**
