### PR TITLE
fix install: pkg-config, *Config.cmake instead of Find*.cmake

### PR DESCRIPTION
**Pull request by Nic30**

### CODE REVIEW

**Comment by Nic30** [comment]
solves issue #95

**Comment by Nic30** [comment]
The problems which were uncovered in this patch are happening also in current version, they are just not checked.

**Comment by flexferrum** [comment]
> The problems which were uncovered in this patch are happening also in current version, they are just not checked.

Hm... Due to travis build logs, the problems occurred when building with externally-provided (i. e. system) boost package.

**Comment by flexferrum** [comment]
Integrated as #102

**Pull request closed without merging**
