### PR TITLE
Add escape filter

### PR DESCRIPTION
**Pull request by morenol**
Solves https://github.com/jinja2cpp/Jinja2Cpp/issues/140

Still work in progress, not sure how to test the quotes  (‘, ”).

### CODE REVIEW

**Comment by flexferrum** [comment]
> Still work in progress, not sure how to test the quotes (‘, ”).

Thanks for contributing! What the exact problem with test for quotes?

**Comment by morenol** [comment]
> > Still work in progress, not sure how to test the quotes (‘, ”).
> 
> Thanks for contributing! What the exact problem with test for quotes?

I think that I solved that, I had to escape both the quotes and the backslash
`                            InputOutputPair{"'\\\"\\'' | escape | pprint", "'&#34;&#39;'"}
`

**Comment by flexferrum** [comment]
> I think that I solved that, I had to escape both the quotes and the backslash
> ` InputOutputPair{"'\\\"\\'' | escape | pprint", "'&#34;&#39;'"}`

Another approach is to use raw-string literals: ` InputOutputPair{R"('\"\'' | escape | pprint)", "'&#34;&#39;'"}`

But your current solution is ok as well.

**Comment by flexferrum** [comment]
@morenol , sorry, I made a mistake when was resolving conflicts of your PR and new master. I missed the `break` statement. Could you provide a fix?

**Comment by morenol** [comment]
Done!

**Comment by flexferrum** [comment]
Thanks!

**Comment by flexferrum** [comment]
@morenol I can merge your PR now or wait till the October, 1st. What would your prefer?

**Comment by morenol** [comment]
Merge, I hope to do more of them in October!

**Comment by morenol** [comment]
I noticed that I haven't edited the readme, I'm going to do that, Is it ok?

**Comment by flexferrum** [comment]
> I noticed that I haven't edited the readme, I'm going to do that, Is it ok?

It's ok. I'm preparing the big PR for preparation to the version 1.0.0 release, so I'll edit the readme in any case.

**Pull request merged**
